/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package models.Gui;

import java.beans.PropertyVetoException;
import java.sql.Connection;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;
import repository.DbConnection;

/**
 *
 * @author loren
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dskPrincipal = new javax.swing.JDesktopPane();
        mnuPrincipal = new javax.swing.JMenuBar();
        mnuInicio = new javax.swing.JMenu();
        mnuInicioSobre = new javax.swing.JMenuItem();
        mnuInicioSair = new javax.swing.JMenuItem();
        mnuAtend = new javax.swing.JMenu();
        mnuCadastroArtista = new javax.swing.JMenuItem();
        mnuAtendCadastrarPaciente = new javax.swing.JMenuItem();
        mnuAtendCadastrarMedico = new javax.swing.JMenuItem();
        mnuAtendCadastrarEnfermeiro = new javax.swing.JMenuItem();
        mnuAtendTriagem = new javax.swing.JMenuItem();
        mnuAtendAtendimentoMedico = new javax.swing.JMenuItem();
        mnuConsulta = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout dskPrincipalLayout = new javax.swing.GroupLayout(dskPrincipal);
        dskPrincipal.setLayout(dskPrincipalLayout);
        dskPrincipalLayout.setHorizontalGroup(
            dskPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 757, Short.MAX_VALUE)
        );
        dskPrincipalLayout.setVerticalGroup(
            dskPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 557, Short.MAX_VALUE)
        );

        mnuInicio.setText("Início ");
        mnuInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuInicioActionPerformed(evt);
            }
        });

        mnuInicioSobre.setText("Sobre");
        mnuInicioSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuInicioSobreActionPerformed(evt);
            }
        });
        mnuInicio.add(mnuInicioSobre);

        mnuInicioSair.setText("Sair");
        mnuInicioSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuInicioSairActionPerformed(evt);
            }
        });
        mnuInicio.add(mnuInicioSair);

        mnuPrincipal.add(mnuInicio);

        mnuAtend.setText("Atendimento");
        mnuAtend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAtendActionPerformed(evt);
            }
        });

        mnuCadastroArtista.setText("Cadastrar Artista");
        mnuCadastroArtista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadastroArtistaActionPerformed(evt);
            }
        });
        mnuAtend.add(mnuCadastroArtista);

        mnuAtendCadastrarPaciente.setText("Cadastrar Paciente");
        mnuAtendCadastrarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAtendCadastrarPacienteActionPerformed(evt);
            }
        });
        mnuAtend.add(mnuAtendCadastrarPaciente);

        mnuAtendCadastrarMedico.setText("Cadastrar Médico");
        mnuAtendCadastrarMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAtendCadastrarMedicoActionPerformed(evt);
            }
        });
        mnuAtend.add(mnuAtendCadastrarMedico);

        mnuAtendCadastrarEnfermeiro.setText("Cadastrar Enfermeiro");
        mnuAtendCadastrarEnfermeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAtendCadastrarEnfermeiroActionPerformed(evt);
            }
        });
        mnuAtend.add(mnuAtendCadastrarEnfermeiro);

        mnuAtendTriagem.setText("Triagem paciente");
        mnuAtendTriagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAtendTriagemActionPerformed(evt);
            }
        });
        mnuAtend.add(mnuAtendTriagem);

        mnuAtendAtendimentoMedico.setText("Atendimento médico");
        mnuAtendAtendimentoMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAtendAtendimentoMedicoActionPerformed(evt);
            }
        });
        mnuAtend.add(mnuAtendAtendimentoMedico);

        mnuConsulta.setText("Consulta");
        mnuConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuConsultaActionPerformed(evt);
            }
        });
        mnuAtend.add(mnuConsulta);

        mnuPrincipal.add(mnuAtend);

        setJMenuBar(mnuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 757, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(dskPrincipal, javax.swing.GroupLayout.Alignment.TRAILING))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 557, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(dskPrincipal))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuInicioSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuInicioSobreActionPerformed
        // TODO add your handling code here:
        attachInternalFrame(Sobre.getInstance());
    }//GEN-LAST:event_mnuInicioSobreActionPerformed

    private void mnuInicioSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuInicioSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_mnuInicioSairActionPerformed

    private void mnuInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuInicioActionPerformed

    private void mnuAtendCadastrarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAtendCadastrarPacienteActionPerformed
        // TODO add your handling code here:
//        attachInternalFrame(CadastroPaciente.getInstance());
    }//GEN-LAST:event_mnuAtendCadastrarPacienteActionPerformed

    private void mnuAtendCadastrarMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAtendCadastrarMedicoActionPerformed
        // TODO add your handling code here:
//        attachInternalFrame(CadastroMedico.getInstance());
    }//GEN-LAST:event_mnuAtendCadastrarMedicoActionPerformed

    private void mnuAtendCadastrarEnfermeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAtendCadastrarEnfermeiroActionPerformed
        // TODO add your handling code here:
//        attachInternalFrame(CadastroEnfermeiro.getInstance());
    }//GEN-LAST:event_mnuAtendCadastrarEnfermeiroActionPerformed

    private void mnuAtendTriagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAtendTriagemActionPerformed
        // TODO add your handling code here:
//        attachInternalFrame(TriagemPaciente.getInstance());
    }//GEN-LAST:event_mnuAtendTriagemActionPerformed

    private void mnuAtendAtendimentoMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAtendAtendimentoMedicoActionPerformed
        // TODO add your handling code here:
//        attachInternalFrame(AtendimentoMedico.getInstance());
    }//GEN-LAST:event_mnuAtendAtendimentoMedicoActionPerformed

    private void mnuConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuConsultaActionPerformed
        // TODO add your handling code here:
//        attachInternalFrame(ConsultaPaciente.getInstance());
    }//GEN-LAST:event_mnuConsultaActionPerformed

    private void mnuAtendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAtendActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuAtendActionPerformed

    private void mnuCadastroArtistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadastroArtistaActionPerformed
        // TODO add your handling code here:
        attachInternalFrame(CadastroArtista.getInstance());
    }//GEN-LAST:event_mnuCadastroArtistaActionPerformed

    private void attachInternalFrame(JInternalFrame window) {
        // Attach internal window to desktop pane
        if (!window.isVisible()) {
            window.setVisible(true);
            dskPrincipal.add(window);
        }

        // Focus and restore the internal window
        try {
            window.setSelected(true);
            window.setIcon(false);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Principal.class.getName())
                    .log(Level.INFO, null, ex);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        Connection conn = DbConnection.getConnection();
        
        System.out.println("> " + conn);
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Principal().setVisible(true);
        });
        
//        Medico medico = new Medico();
//        Enfermeiro enfermeiro = new Enfermeiro();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dskPrincipal;
    private javax.swing.JMenu mnuAtend;
    private javax.swing.JMenuItem mnuAtendAtendimentoMedico;
    private javax.swing.JMenuItem mnuAtendCadastrarEnfermeiro;
    private javax.swing.JMenuItem mnuAtendCadastrarMedico;
    private javax.swing.JMenuItem mnuAtendCadastrarPaciente;
    private javax.swing.JMenuItem mnuAtendTriagem;
    private javax.swing.JMenuItem mnuCadastroArtista;
    private javax.swing.JMenuItem mnuConsulta;
    private javax.swing.JMenu mnuInicio;
    private javax.swing.JMenuItem mnuInicioSair;
    private javax.swing.JMenuItem mnuInicioSobre;
    private javax.swing.JMenuBar mnuPrincipal;
    // End of variables declaration//GEN-END:variables
}
